### ISSUE TITLE
Error during the creation of a Python code env

### ISSUE THREAD

**Issue by Marsobad** [vinshet/Natifdataiku#1]
# Issue
The code env creation of the plugin fails because of two conflicting versions of Pandas: 
![Screenshot 2021-04-14 at 17 22 08](https://user-images.githubusercontent.com/29501817/114736382-55577a80-9d46-11eb-9563-3cf1d8bb4b25.png)
# Fix
Please set installCorePackages to false in [desc.json](https://github.com/vinshet/Natifdataiku/blob/149ed0e65c4d59ab35979eee56a81224f7ec9a57/code-env/python/desc.json#L8).
The core package of Dataiku relies on Pandas 0.23.4 which triggers the conflict with Pandas 1.1.3 from the requirements

**Comment by vinshet** [comment]
Updated the value to false.
