### ISSUE TITLE
Pandas version is not supported by the Dataiku API for Python 3.7 

### ISSUE THREAD

**Issue by Marsobad** [vinshet/Natifdataiku#2]
Actually, I was wrong to tell you to remove the core packages yesterday. Dataiku API does not support pandas versions == 1.1.3 and it results in the failing of the 'toDataset' recipe with a Python 3.7 code env. Instead, the best practise is to use Dataiku's default packages and remove pandas and requests from requirements as it part of Dataiku's default packages. Also note that Dataiku does not support Python 3.8
So, you should set installCorePackages to true in desc.json : 
`{
    "acceptedPythonInterpreters": [
        "PYTHON36",
        "PYTHON37"
    ],
    "forceConda": false,
    "installCorePackages": true,
    "installJupyterSupport": false
}`
You should also remove pandas and requests from `requirements.txt`. 
Thank you for your patience and sorry for this confusion

**Comment by vinshet** [comment]
It's no problem! Made the necessary changes.
